/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Ruta;

/**
 *
 * @author debor
 */
public class FormularioRuta extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioHorario
     */
    public FormularioRuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlHSalida = new javax.swing.JLabel();
        jlHLlegada = new javax.swing.JLabel();
        jbGuardarHorario = new javax.swing.JButton();
        jtfDestino = new javax.swing.JTextField();
        jlDestino = new javax.swing.JLabel();
        jlOrigen = new javax.swing.JLabel();
        jtfOrigen = new javax.swing.JTextField();
        jbGuardarHorarioRuta = new javax.swing.JButton();
        jlRutaExistente = new javax.swing.JLabel();
        jcbRutasExistentes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jlHorario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlRutaNueva = new javax.swing.JLabel();
        jtfHoraSalida = new javax.swing.JTextField();
        jtfMinSalida = new javax.swing.JTextField();
        jlSeparadorHoraS = new javax.swing.JLabel();
        jtfHoraLlegada = new javax.swing.JTextField();
        jtfMinLlegada = new javax.swing.JTextField();
        jlSeparadorHoraL = new javax.swing.JLabel();

        setClosable(true);

        jlTitulo.setBackground(new java.awt.Color(0, 0, 125));
        jlTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Formulario ruta");

        jlHSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHSalida.setText("Horario de salida");

        jlHLlegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHLlegada.setText("Horario de llegada");

        jbGuardarHorario.setText("Guardar solo Horario (con Ruta existente)");

        jlDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDestino.setText("Destino");

        jlOrigen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOrigen.setText("Origen");

        jbGuardarHorarioRuta.setText("Guardar Ruta y Horario");

        jlRutaExistente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlRutaExistente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRutaExistente.setText("Ruta existente");

        jlHorario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHorario.setText("Horario");

        jlRutaNueva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlRutaNueva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRutaNueva.setText("Ruta nueva");

        jlSeparadorHoraS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSeparadorHoraS.setText(":");

        jlSeparadorHoraL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSeparadorHoraL.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlRutaNueva)
                .addGap(182, 182, 182))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jlRutaExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbGuardarHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbGuardarHorarioRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbRutasExistentes, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlHLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jlOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlSeparadorHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMinSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlSeparadorHoraL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMinLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(27, 27, 27)
                .addComponent(jlHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlHSalida)
                    .addComponent(jlHLlegada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMinSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSeparadorHoraS)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfMinLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlSeparadorHoraL)))
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jlRutaNueva)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDestino)
                    .addComponent(jlOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlRutaExistente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbRutasExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jbGuardarHorario)
                .addGap(18, 18, 18)
                .addComponent(jbGuardarHorarioRuta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbGuardarHorario;
    private javax.swing.JButton jbGuardarHorarioRuta;
    private javax.swing.JComboBox<Ruta> jcbRutasExistentes;
    private javax.swing.JLabel jlDestino;
    private javax.swing.JLabel jlHLlegada;
    private javax.swing.JLabel jlHSalida;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlOrigen;
    private javax.swing.JLabel jlRutaExistente;
    private javax.swing.JLabel jlRutaNueva;
    private javax.swing.JLabel jlSeparadorHoraL;
    private javax.swing.JLabel jlSeparadorHoraS;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfDestino;
    private javax.swing.JTextField jtfHoraLlegada;
    private javax.swing.JTextField jtfHoraSalida;
    private javax.swing.JTextField jtfMinLlegada;
    private javax.swing.JTextField jtfMinSalida;
    private javax.swing.JTextField jtfOrigen;
    // End of variables declaration//GEN-END:variables
}
